const actionTypes = {
  POST_AUTHENTICATION_SESSION_NEW: "POST_AUTHENTICATION_SESSION_NEW",
  GET_MOVIE_NOW_PLAYING: "GET_MOVIE_NOW_PLAYING",
  GET_MOVIE_POPULAR: "GET_MOVIE_POPULAR",
  GET_MOVIE_TOP_RATED: "GET_MOVIE_TOP_RATED",
  GET_ACCOUNT_FAVORITE_MOVIES: "GET_ACCOUNT_FAVORITE_MOVIES",
  GET_ACCOUNT_WATCHLIST_MOVIES: "GET_ACCOUNT_WATCHLIST_MOVIES",
  GET_MOVIE_UPCOMING: "GET_MOVIE_UPCOMING",
  GET_AUTHENTICATION_TOKEN_NEW: "GET_AUTHENTICATION_TOKEN_NEW",
  ACCOUNT_FAVORITE: "ACCOUNT_FAVORITE",
  GET_SEARCH_MOVIE: "GET_SEARCH_MOVIE",
  GET_MOVIE: "GET_MOVIE",
  GET_MOVIE_IMAGES: "GET_MOVIE_IMAGES",
  SHOW_TOAST: "SHOW_TOAST",
  HIDE_TOAST: "HIDE_TOAST",
  ACCOUNT_WATCHLIST: "ACCOUNT_WATCHLIST",
  UPDATE_ID: "UPDATE_ID"
};

export default actionTypes;
